{
    "name": "Employee Access Control",
    "version": "19.0.1.0.0",
    "summary": "Configuration foundation for employee access management",
    "author": "aamk",
    "category": "Human Resources",
    "license": "LGPL-3",
    "depends": ["base", "web", "mail"],
    "data": [
        "data/company_data.xml",
        "security/employee_access_security.xml",
        "security/ir.model.access.csv",
        "data/application_data.xml",
        "data/access_group_data.xml",
        "data/approval_rule_data.xml",
        "views/request_views.xml",
        "views/facility_views.xml",
        "views/system_tag_views.xml",
        "views/system_views.xml",
        "views/application_views.xml",
        "views/access_group_views.xml",
        "views/approval_rule_views.xml",
        "views/provisioning_views.xml",
        "views/employee_access_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "employee_access_control/static/src/js/dashboard_action.js",
            "employee_access_control/static/src/xml/dashboard_action.xml",
            "employee_access_control/static/src/scss/dashboard_action.scss",
            "employee_access_control/static/src/js/company_header_lock.js",
            "employee_access_control/static/src/js/request_date_field.js",
            "employee_access_control/static/src/js/application_role_dropdowns.js",
            "employee_access_control/static/src/xml/application_role_dropdowns.xml",
            "employee_access_control/static/src/scss/application_role_dropdowns.scss",
        ],
    },
    "installable": True,
    "application": True,
}
